"""add dashboard sessions

Phase 4D, F1 (dashboard authentication): a session table for
`POST /v1/auth/login`/`POST /v1/auth/logout`/`GET /v1/auth/session`,
mirroring `api_keys`'s own shape -- only `token_hash` is ever compared
against a presented session token (see app/security/sessions.py), never a
raw token, which is not persisted anywhere once issued. `revoked_at` is
what makes logout an immediate, real revocation rather than a wait for
natural `expires_at` expiry. See app/db/models/dashboard_session.py and
app/services/auth.py.

Revision ID: ad0d41d7d82c
Revises: 2925f09e0276
Create Date: 2026-09-18 15:34:55.043733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0d41d7d82c'
down_revision: Union[str, Sequence[str], None] = '2925f09e0276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dashboard_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_dashboard_sessions_token_hash'))
    )
    op.create_index('ix_dashboard_sessions_user_id', 'dashboard_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dashboard_sessions_user_id', table_name='dashboard_sessions')
    op.drop_table('dashboard_sessions')
    # ### end Alembic commands ###
